spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meongcare
    username: root
    password: "@sun0896180"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    default_batch_fetch_size: 100
    database: mysql
    show-sql: true
    generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379
  logging:
    level:
      org:
        springframework:
          jdbc: debug

jwt:
  secretKey: asdkj1b1jahdo1iu3ht512k7j4asdfajksdfjklh1jk23112312
  access:
    expiration: 36000000000
    header: AccessToken
  refresh:
    expiration: 1209600000
    header: RefreshToken

cloud:
  aws:
    s3:
      bucket: meongcare-second-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA6DKD6QRBSPMAJH6X
      secret-key: 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

env:
  image-url:
    logo: https://meongcare-bucket.s3.ap-northeast-2.amazonaws.com/meongcare/static/meongcare_LOGO.PNG
