version: "3"
services:
  blue:
    image: meongcare/dev
    container_name: blue
    ports:
      - 8081:8080

  green:
    image: meongcare/dev
    container_name: green
    ports:
      - 8082:8080

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
