name: CI/CD 

on:
  push:
    branches: [ "feature/32" ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |  
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          
  notification:
    name: Slack 배포 알림
    runs-on: ubuntu-latest
    if: ${{ always() }} 
    needs: [CI-CD]
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Bot
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
